### ISSUE TITLE
Console.logs

### ISSUE THREAD

**Issue by GavinThomas1192** [simformsolutions/react-native-spinner-button#7]
Hey, love this package!
Was quick and worked out of box. 

Can you remove these console . logs?

I can also do a PR but not for a couple days..
Spinner.js 44-45
Thanks!

I went ahead and did a PR 
https://github.com/simformsolutions/react-native-spinner-button/pull/8

**Comment by simformsolutions** [comment]
Thanks, @GavinThomas1192. I will merge the PR
